format = """
$username\
[ ](bg:#FF6C83 fg:#E077FF)\
$directory\
[ ](fg:#FF6C83 bg:#FCA17D)\
$git_branch\
$git_status\
[ ](fg:#FCA17D bg:#FFD47E)\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
[ ](fg:#FFD47E bg:#9fdE7f)\
$docker_context\
[ ](fg:#9fdE7f bg:#809afa)\
$time\
[
](fg:#809afa)\
$character
"""
right_format = """$cmd_duration"""

# Disable the blank line at the start of the prompt
add_newline = false

# You can also replace your username with a neat symbol like  to save some space
[username]
show_always = true
style_user = "bg:#E077FF fg:#000000"
style_root = "bg:#E077FF"
format = '[   $user ]($style)'

[character]
success_symbol = "[➤](bold green)"
error_symbol = "[➤](bold red)"

[cmd_duration]
min_time = 1
format = "[$duration](bold yellow) "

[directory]
style = "bg:#FF6C83 fg:#000000"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Desktop" = ""
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"Public" = " "
"Templates" = " "
"Videos" = " "
"Warpinator" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[c]
symbol = " "
style = "bg:#FFD47E fg:#000000"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#9fdE7f fg:#000000"
format = '[ $symbol $context ]($style) $path'

[elixir]
symbol = " "
style = "bg:#FFD47E fg:#000000"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:#FFD47E fg:#000000"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:#FCA17D fg:#000000"
format = '[ $symbol $branch]($style)'

[git_status]
style = "bg:#FCA17D fg:#000000"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:#FFD47E fg:#000000 fg:#000000"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:#FFD47E fg:#000000"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#FFD47E fg:#000000"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:#FFD47E fg:#000000"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#FFD47E fg:#000000"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = " "
style = "bg:#FFD47E fg:#000000"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:#FFD47E fg:#000000"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#809afa fg:#000000"
format = '[ ♥ $time ]($style)'
